const CITY_LIST = [{
    "CityID": 1,
    "CityName": "北京",
    "HasCompany": true,
    "IsHot": 1,
    "ProID": 1,
    "QuanPin": "BEIJING",
    "SortID": 11
  }, {
    "CityID": 2,
    "CityName": "天津",
    "HasCompany": true,
    "IsHot": 1,
    "ProID": 2,
    "QuanPin": "TIANJIN",
    "SortID": 15
  }, {
    "CityID": 3,
    "CityName": "上海",
    "HasCompany": true,
    "IsHot": 1,
    "ProID": 9,
    "QuanPin": "SHANGHAI",
    "SortID": 4
  }, {
    "CityID": 4,
    "CityName": "重庆",
    "HasCompany": true,
    "IsHot": 1,
    "ProID": 27,
    "QuanPin": "CHONGQING",
    "SortID": 12
  }, {
    "CityID": 5,
    "CityName": "邯郸",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 3,
    "QuanPin": "HANDAN"
  }, {
    "CityID": 6,
    "CityName": "石家庄",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 3,
    "QuanPin": "SHIJIAZHUANG"
  }, {
    "CityID": 7,
    "CityName": "保定",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 3,
    "QuanPin": "BAODING"
  }, {
    "CityID": 8,
    "CityName": "张家口",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 3,
    "QuanPin": "ZHANGJIAKOU"
  }, {
    "CityID": 9,
    "CityName": "承德",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 3,
    "QuanPin": "CHENGDE"
  }, {
    "CityID": 10,
    "CityName": "唐山",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 3,
    "QuanPin": "TANGSHAN"
  }, {
    "CityID": 11,
    "CityName": "廊坊",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 3,
    "QuanPin": "LANGFANG"
  }, {
    "CityID": 12,
    "CityName": "沧州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 3,
    "QuanPin": "CANGZHOU"
  }, {
    "CityID": 13,
    "CityName": "衡水",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 3,
    "QuanPin": "HENGSHUI"
  }, {
    "CityID": 14,
    "CityName": "邢台",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 3,
    "QuanPin": "XINGTAI"
  }, {
    "CityID": 15,
    "CityName": "秦皇岛",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 3,
    "QuanPin": "QINHUANGDAO"
  }, {
    "CityID": 16,
    "CityName": "朔州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 4,
    "QuanPin": "SHUOZHOU"
  }, {
    "CityID": 17,
    "CityName": "忻州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 4,
    "QuanPin": "XINZHOU"
  }, {
    "CityID": 18,
    "CityName": "太原",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 4,
    "QuanPin": "TAIYUAN"
  }, {
    "CityID": 19,
    "CityName": "大同",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 4,
    "QuanPin": "DATONG"
  }, {
    "CityID": 20,
    "CityName": "阳泉",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 4,
    "QuanPin": "YANGQUAN"
  }, {
    "CityID": 21,
    "CityName": "晋中",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 4,
    "QuanPin": "JINZHONG"
  }, {
    "CityID": 22,
    "CityName": "长治",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 4,
    "QuanPin": "CHANGZHI"
  }, {
    "CityID": 23,
    "CityName": "晋城",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 4,
    "QuanPin": "JINCHENG"
  }, {
    "CityID": 24,
    "CityName": "临汾",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 4,
    "QuanPin": "LINFEN"
  }, {
    "CityID": 25,
    "CityName": "吕梁",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 4,
    "QuanPin": "LVLIANG"
  }, {
    "CityID": 26,
    "CityName": "运城",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 4,
    "QuanPin": "YUNCHENG"
  }, {
    "CityID": 27,
    "CityName": "沈阳",
    "HasCompany": false,
    "IsHot": 1,
    "ProID": 6,
    "QuanPin": "SHENYANG"
  }, {
    "CityID": 28,
    "CityName": "铁岭",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 6,
    "QuanPin": "TIELING"
  }, {
    "CityID": 29,
    "CityName": "大连",
    "HasCompany": false,
    "IsHot": 1,
    "ProID": 6,
    "QuanPin": "DALIAN"
  }, {
    "CityID": 30,
    "CityName": "鞍山",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 6,
    "QuanPin": "ANSHAN"
  }, {
    "CityID": 31,
    "CityName": "抚顺",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 6,
    "QuanPin": "FUSHUN"
  }, {
    "CityID": 32,
    "CityName": "本溪",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 6,
    "QuanPin": "BENXI"
  }, {
    "CityID": 33,
    "CityName": "丹东",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 6,
    "QuanPin": "DANDONG"
  }, {
    "CityID": 34,
    "CityName": "锦州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 6,
    "QuanPin": "JINZHOU"
  }, {
    "CityID": 35,
    "CityName": "营口",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 6,
    "QuanPin": "YINGKOU"
  }, {
    "CityID": 36,
    "CityName": "阜新",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 6,
    "QuanPin": "FUXIN"
  }, {
    "CityID": 37,
    "CityName": "辽阳",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 6,
    "QuanPin": "LIAOYANG"
  }, {
    "CityID": 38,
    "CityName": "朝阳",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 6,
    "QuanPin": "CHAOYANG"
  }, {
    "CityID": 39,
    "CityName": "盘锦",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 6,
    "QuanPin": "PANJIN"
  }, {
    "CityID": 40,
    "CityName": "葫芦岛",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 6,
    "QuanPin": "HULUDAO"
  }, {
    "CityID": 41,
    "CityName": "长春",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 7,
    "QuanPin": "CHANGCHUN"
  }, {
    "CityID": 42,
    "CityName": "吉林",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 7,
    "QuanPin": "JILIN"
  }, {
    "CityID": 43,
    "CityName": "延边",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 7,
    "QuanPin": "YANBIAN"
  }, {
    "CityID": 44,
    "CityName": "四平",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 7,
    "QuanPin": "SIPING"
  }, {
    "CityID": 45,
    "CityName": "通化",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 7,
    "QuanPin": "TONGHUA"
  }, {
    "CityID": 46,
    "CityName": "白城",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 7,
    "QuanPin": "BAICHENG"
  }, {
    "CityID": 47,
    "CityName": "辽源",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 7,
    "QuanPin": "LIAOYUAN"
  }, {
    "CityID": 48,
    "CityName": "松原",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 7,
    "QuanPin": "SONGYUAN"
  }, {
    "CityID": 49,
    "CityName": "白山",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 7,
    "QuanPin": "BAISHAN"
  }, {
    "CityID": 50,
    "CityName": "哈尔滨",
    "HasCompany": false,
    "IsHot": 1,
    "ProID": 8,
    "QuanPin": "HAERBIN"
  }, {
    "CityID": 51,
    "CityName": "齐齐哈尔",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 8,
    "QuanPin": "QIQIHAER"
  }, {
    "CityID": 52,
    "CityName": "鸡西",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 8,
    "QuanPin": "JIXI"
  }, {
    "CityID": 53,
    "CityName": "牡丹江",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 8,
    "QuanPin": "MUDANJIANG"
  }, {
    "CityID": 54,
    "CityName": "七台河",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 8,
    "QuanPin": "QITAIHE"
  }, {
    "CityID": 55,
    "CityName": "佳木斯",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 8,
    "QuanPin": "JIAMUSI"
  }, {
    "CityID": 56,
    "CityName": "鹤岗",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 8,
    "QuanPin": "HEGANG"
  }, {
    "CityID": 57,
    "CityName": "双鸭山",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 8,
    "QuanPin": "SHUANGYASHAN"
  }, {
    "CityID": 58,
    "CityName": "绥化",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 8,
    "QuanPin": "SUIHUA"
  }, {
    "CityID": 59,
    "CityName": "黑河",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 8,
    "QuanPin": "HEIHE"
  }, {
    "CityID": 60,
    "CityName": "大兴安岭",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 8,
    "QuanPin": "DAXINGANLING"
  }, {
    "CityID": 61,
    "CityName": "伊春",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 8,
    "QuanPin": "YICHUN"
  }, {
    "CityID": 62,
    "CityName": "大庆",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 8,
    "QuanPin": "DAQING"
  }, {
    "CityID": 63,
    "CityName": "南京",
    "HasCompany": true,
    "IsHot": 1,
    "ProID": 10,
    "QuanPin": "NANJING",
    "SortID": 5
  }, {
    "CityID": 64,
    "CityName": "无锡",
    "HasCompany": true,
    "IsHot": 1,
    "ProID": 10,
    "QuanPin": "WUXI",
    "SortID": 8
  }, {
    "CityID": 65,
    "CityName": "镇江",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 10,
    "QuanPin": "ZHENJIANG"
  }, {
    "CityID": 66,
    "CityName": "苏州",
    "HasCompany": true,
    "IsHot": 1,
    "ProID": 10,
    "QuanPin": "SUZHOU",
    "SortID": 1
  }, {
    "CityID": 67,
    "CityName": "南通",
    "HasCompany": true,
    "IsHot": 1,
    "ProID": 10,
    "QuanPin": "NANTONG",
    "SortID": 14
  }, {
    "CityID": 68,
    "CityName": "扬州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 10,
    "QuanPin": "YANGZHOU"
  }, {
    "CityID": 69,
    "CityName": "盐城",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 10,
    "QuanPin": "YANCHENG"
  }, {
    "CityID": 70,
    "CityName": "徐州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 10,
    "QuanPin": "XUZHOU"
  }, {
    "CityID": 71,
    "CityName": "淮安",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 10,
    "QuanPin": "HUAIAN"
  }, {
    "CityID": 72,
    "CityName": "连云港",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 10,
    "QuanPin": "LIANYUNGANG"
  }, {
    "CityID": 73,
    "CityName": "常州",
    "HasCompany": true,
    "IsHot": 1,
    "ProID": 10,
    "QuanPin": "CHANGZHOU",
    "SortID": 18
  }, {
    "CityID": 74,
    "CityName": "泰州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 10,
    "QuanPin": "TAIZHOU"
  }, {
    "CityID": 75,
    "CityName": "宿迁",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 10,
    "QuanPin": "SUQIAN"
  }, {
    "CityID": 76,
    "CityName": "舟山",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 11,
    "QuanPin": "ZHOUSHAN"
  }, {
    "CityID": 77,
    "CityName": "衢州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 11,
    "QuanPin": "QUZHOU"
  }, {
    "CityID": 78,
    "CityName": "杭州",
    "HasCompany": true,
    "IsHot": 1,
    "ProID": 11,
    "QuanPin": "HANGZHOU",
    "SortID": 2
  }, {
    "CityID": 79,
    "CityName": "湖州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 11,
    "QuanPin": "HUZHOU"
  }, {
    "CityID": 80,
    "CityName": "嘉兴",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 11,
    "QuanPin": "JIAXING"
  }, {
    "CityID": 81,
    "CityName": "宁波",
    "HasCompany": true,
    "IsHot": 1,
    "ProID": 11,
    "QuanPin": "NINGBO",
    "SortID": 7
  }, {
    "CityID": 82,
    "CityName": "绍兴",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 11,
    "QuanPin": "SHAOXING"
  }, {
    "CityID": 83,
    "CityName": "温州",
    "HasCompany": false,
    "IsHot": 1,
    "ProID": 11,
    "QuanPin": "WENZHOU"
  }, {
    "CityID": 84,
    "CityName": "丽水",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 11,
    "QuanPin": "LISHUI"
  }, {
    "CityID": 85,
    "CityName": "金华",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 11,
    "QuanPin": "JINHUA"
  }, {
    "CityID": 86,
    "CityName": "台州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 11,
    "QuanPin": "TAIZHOU1"
  }, {
    "CityID": 87,
    "CityName": "合肥",
    "HasCompany": true,
    "IsHot": 1,
    "ProID": 12,
    "QuanPin": "HEFEI",
    "SortID": 16
  }, {
    "CityID": 88,
    "CityName": "芜湖",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 12,
    "QuanPin": "WUHU"
  }, {
    "CityID": 89,
    "CityName": "蚌埠",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 12,
    "QuanPin": "BENGBU"
  }, {
    "CityID": 90,
    "CityName": "淮南",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 12,
    "QuanPin": "HUAINAN"
  }, {
    "CityID": 91,
    "CityName": "马鞍山",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 12,
    "QuanPin": "MAANSHAN"
  }, {
    "CityID": 92,
    "CityName": "淮北",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 12,
    "QuanPin": "HUAIBEI"
  }, {
    "CityID": 93,
    "CityName": "铜陵",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 12,
    "QuanPin": "TONGLING"
  }, {
    "CityID": 94,
    "CityName": "安庆",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 12,
    "QuanPin": "ANQING"
  }, {
    "CityID": 95,
    "CityName": "黄山",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 12,
    "QuanPin": "HUANGSHAN"
  }, {
    "CityID": 96,
    "CityName": "滁州",
    "HasCompany": false,
    "IsHot": 1,
    "ProID": 12,
    "QuanPin": "CHUZHOU"
  }, {
    "CityID": 97,
    "CityName": "阜阳",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 12,
    "QuanPin": "FUYANG"
  }, {
    "CityID": 98,
    "CityName": "宿州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 12,
    "QuanPin": "SUZHOU1"
  }, {
    "CityID": 100,
    "CityName": "六安",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 12,
    "QuanPin": "LIUAN"
  }, {
    "CityID": 101,
    "CityName": "亳州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 12,
    "QuanPin": "BOZHOU"
  }, {
    "CityID": 102,
    "CityName": "池州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 12,
    "QuanPin": "CHIZHOU"
  }, {
    "CityID": 103,
    "CityName": "宣城",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 12,
    "QuanPin": "XUANCHENG"
  }, {
    "CityID": 104,
    "CityName": "福州",
    "HasCompany": false,
    "IsHot": 1,
    "ProID": 13,
    "QuanPin": "FUZHOU"
  }, {
    "CityID": 105,
    "CityName": "厦门",
    "HasCompany": false,
    "IsHot": 1,
    "ProID": 13,
    "QuanPin": "XIAMEN"
  }, {
    "CityID": 106,
    "CityName": "宁德",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 13,
    "QuanPin": "NINGDE"
  }, {
    "CityID": 107,
    "CityName": "莆田",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 13,
    "QuanPin": "PUTIAN"
  }, {
    "CityID": 108,
    "CityName": "泉州",
    "HasCompany": false,
    "IsHot": 1,
    "ProID": 13,
    "QuanPin": "QUANZHOU"
  }, {
    "CityID": 109,
    "CityName": "漳州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 13,
    "QuanPin": "ZHANGZHOU"
  }, {
    "CityID": 110,
    "CityName": "龙岩",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 13,
    "QuanPin": "LONGYAN"
  }, {
    "CityID": 111,
    "CityName": "三明",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 13,
    "QuanPin": "SANMING"
  }, {
    "CityID": 112,
    "CityName": "南平",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 13,
    "QuanPin": "NANPING"
  }, {
    "CityID": 113,
    "CityName": "鹰潭",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 14,
    "QuanPin": "YINGTAN"
  }, {
    "CityID": 114,
    "CityName": "新余",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 14,
    "QuanPin": "XINYU"
  }, {
    "CityID": 115,
    "CityName": "南昌",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 14,
    "QuanPin": "NANCHANG"
  }, {
    "CityID": 116,
    "CityName": "九江",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 14,
    "QuanPin": "JIUJIANG"
  }, {
    "CityID": 117,
    "CityName": "上饶",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 14,
    "QuanPin": "SHANGRAO"
  }, {
    "CityID": 118,
    "CityName": "抚州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 14,
    "QuanPin": "FUZHOU1"
  }, {
    "CityID": 119,
    "CityName": "宜春",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 14,
    "QuanPin": "YICHUN"
  }, {
    "CityID": 120,
    "CityName": "吉安",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 14,
    "QuanPin": "JIAN"
  }, {
    "CityID": 121,
    "CityName": "赣州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 14,
    "QuanPin": "GANZHOU"
  }, {
    "CityID": 122,
    "CityName": "景德镇",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 14,
    "QuanPin": "JINGDEZHEN"
  }, {
    "CityID": 123,
    "CityName": "萍乡",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 14,
    "QuanPin": "PINGXIANG"
  }, {
    "CityID": 124,
    "CityName": "菏泽",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 15,
    "QuanPin": "HEZE"
  }, {
    "CityID": 125,
    "CityName": "济南",
    "HasCompany": false,
    "IsHot": 1,
    "ProID": 15,
    "QuanPin": "JINAN"
  }, {
    "CityID": 126,
    "CityName": "青岛",
    "HasCompany": true,
    "IsHot": 1,
    "ProID": 15,
    "QuanPin": "QINGDAO",
    "SortID": 3
  }, {
    "CityID": 127,
    "CityName": "淄博",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 15,
    "QuanPin": "ZIBO"
  }, {
    "CityID": 128,
    "CityName": "德州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 15,
    "QuanPin": "DEZHOU"
  }, {
    "CityID": 129,
    "CityName": "烟台",
    "HasCompany": false,
    "IsHot": 1,
    "ProID": 15,
    "QuanPin": "YANTAI"
  }, {
    "CityID": 130,
    "CityName": "潍坊",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 15,
    "QuanPin": "WEIFANG"
  }, {
    "CityID": 131,
    "CityName": "济宁",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 15,
    "QuanPin": "JINING"
  }, {
    "CityID": 132,
    "CityName": "泰安",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 15,
    "QuanPin": "TAIAN"
  }, {
    "CityID": 133,
    "CityName": "临沂",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 15,
    "QuanPin": "LINYI"
  }, {
    "CityID": 134,
    "CityName": "滨州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 15,
    "QuanPin": "BINZHOU"
  }, {
    "CityID": 135,
    "CityName": "东营",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 15,
    "QuanPin": "DONGYING"
  }, {
    "CityID": 136,
    "CityName": "威海",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 15,
    "QuanPin": "WEIHAI"
  }, {
    "CityID": 137,
    "CityName": "枣庄",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 15,
    "QuanPin": "ZAOZHUANG"
  }, {
    "CityID": 138,
    "CityName": "日照",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 15,
    "QuanPin": "RIZHAO"
  }, {
    "CityID": 139,
    "CityName": "莱芜",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 15,
    "QuanPin": "LAIWU"
  }, {
    "CityID": 140,
    "CityName": "聊城",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 15,
    "QuanPin": "LIAOCHENG"
  }, {
    "CityID": 141,
    "CityName": "商丘",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 16,
    "QuanPin": "SHANGQIU"
  }, {
    "CityID": 142,
    "CityName": "郑州",
    "HasCompany": true,
    "IsHot": 1,
    "ProID": 16,
    "QuanPin": "ZHENGZHOU",
    "SortID": 19
  }, {
    "CityID": 143,
    "CityName": "安阳",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 16,
    "QuanPin": "ANYANG"
  }, {
    "CityID": 144,
    "CityName": "新乡",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 16,
    "QuanPin": "XINXIANG"
  }, {
    "CityID": 145,
    "CityName": "许昌",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 16,
    "QuanPin": "XUCHANG"
  }, {
    "CityID": 146,
    "CityName": "平顶山",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 16,
    "QuanPin": "PINGDINGSHAN"
  }, {
    "CityID": 147,
    "CityName": "信阳",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 16,
    "QuanPin": "XINYANG"
  }, {
    "CityID": 148,
    "CityName": "南阳",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 16,
    "QuanPin": "NANYANG"
  }, {
    "CityID": 149,
    "CityName": "开封",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 16,
    "QuanPin": "KAIFENG"
  }, {
    "CityID": 150,
    "CityName": "洛阳",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 16,
    "QuanPin": "LUOYANG"
  }, {
    "CityID": 151,
    "CityName": "济源",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 16,
    "QuanPin": "JIYUAN"
  }, {
    "CityID": 152,
    "CityName": "焦作",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 16,
    "QuanPin": "JIAOZUO"
  }, {
    "CityID": 153,
    "CityName": "鹤壁",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 16,
    "QuanPin": "HEBI"
  }, {
    "CityID": 154,
    "CityName": "濮阳",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 16,
    "QuanPin": "PUYANG"
  }, {
    "CityID": 155,
    "CityName": "周口",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 16,
    "QuanPin": "ZHOUKOU"
  }, {
    "CityID": 156,
    "CityName": "漯河",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 16,
    "QuanPin": "LUOHE"
  }, {
    "CityID": 157,
    "CityName": "驻马店",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 16,
    "QuanPin": "ZHUMADIAN"
  }, {
    "CityID": 158,
    "CityName": "三门峡",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 16,
    "QuanPin": "SANMENXIA"
  }, {
    "CityID": 159,
    "CityName": "武汉",
    "HasCompany": true,
    "IsHot": 1,
    "ProID": 17,
    "QuanPin": "WUHAN",
    "SortID": 13
  }, {
    "CityID": 160,
    "CityName": "襄阳",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 17,
    "QuanPin": "XIANGFAN"
  }, {
    "CityID": 161,
    "CityName": "鄂州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 17,
    "QuanPin": "EZHOU"
  }, {
    "CityID": 162,
    "CityName": "孝感",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 17,
    "QuanPin": "XIAOGAN"
  }, {
    "CityID": 163,
    "CityName": "黄冈",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 17,
    "QuanPin": "HUANGGANG"
  }, {
    "CityID": 164,
    "CityName": "黄石",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 17,
    "QuanPin": "HUANGSHI"
  }, {
    "CityID": 165,
    "CityName": "咸宁",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 17,
    "QuanPin": "XIANNING"
  }, {
    "CityID": 166,
    "CityName": "荆州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 17,
    "QuanPin": "JINGZHOU"
  }, {
    "CityID": 167,
    "CityName": "宜昌",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 17,
    "QuanPin": "YICHANG"
  }, {
    "CityID": 168,
    "CityName": "恩施",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 17,
    "QuanPin": "ENSHI"
  }, {
    "CityID": 169,
    "CityName": "神农架",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 17,
    "QuanPin": "SHENNONGJIA"
  }, {
    "CityID": 170,
    "CityName": "十堰",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 17,
    "QuanPin": "SHIYAN"
  }, {
    "CityID": 171,
    "CityName": "随州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 17,
    "QuanPin": "SUIZHOU"
  }, {
    "CityID": 172,
    "CityName": "荆门",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 17,
    "QuanPin": "JINGMEN"
  }, {
    "CityID": 173,
    "CityName": "仙桃",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 17,
    "QuanPin": "XIANTAO"
  }, {
    "CityID": 174,
    "CityName": "天门",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 17,
    "QuanPin": "TIANMEN"
  }, {
    "CityID": 175,
    "CityName": "潜江",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 17,
    "QuanPin": "QIANJIANG"
  }, {
    "CityID": 176,
    "CityName": "岳阳",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 18,
    "QuanPin": "YUEYANG"
  }, {
    "CityID": 177,
    "CityName": "长沙",
    "HasCompany": false,
    "IsHot": 1,
    "ProID": 18,
    "QuanPin": "CHANGSHA"
  }, {
    "CityID": 178,
    "CityName": "湘潭",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 18,
    "QuanPin": "XIANGTAN"
  }, {
    "CityID": 179,
    "CityName": "株洲",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 18,
    "QuanPin": "ZHUZHOU"
  }, {
    "CityID": 180,
    "CityName": "衡阳",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 18,
    "QuanPin": "HENGYANG"
  }, {
    "CityID": 181,
    "CityName": "郴州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 18,
    "QuanPin": "CHENZHOU"
  }, {
    "CityID": 182,
    "CityName": "常德",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 18,
    "QuanPin": "CHANGDE"
  }, {
    "CityID": 183,
    "CityName": "益阳",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 18,
    "QuanPin": "YIYANG"
  }, {
    "CityID": 184,
    "CityName": "娄底",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 18,
    "QuanPin": "LOUDI"
  }, {
    "CityID": 185,
    "CityName": "邵阳",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 18,
    "QuanPin": "SHAOYANG"
  }, {
    "CityID": 186,
    "CityName": "湘西",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 18,
    "QuanPin": "XIANGXI"
  }, {
    "CityID": 187,
    "CityName": "张家界",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 18,
    "QuanPin": "ZHANGJIAJIE"
  }, {
    "CityID": 188,
    "CityName": "怀化",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 18,
    "QuanPin": "HUAIHUA"
  }, {
    "CityID": 189,
    "CityName": "永州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 18,
    "QuanPin": "YONGZHOU"
  }, {
    "CityID": 190,
    "CityName": "广州",
    "HasCompany": true,
    "IsHot": 1,
    "ProID": 19,
    "QuanPin": "GUANGZHOU",
    "SortID": 6
  }, {
    "CityID": 191,
    "CityName": "汕尾",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 19,
    "QuanPin": "SHANWEI"
  }, {
    "CityID": 192,
    "CityName": "阳江",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 19,
    "QuanPin": "YANGJIANG"
  }, {
    "CityID": 193,
    "CityName": "揭阳",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 19,
    "QuanPin": "JIEYANG"
  }, {
    "CityID": 194,
    "CityName": "茂名",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 19,
    "QuanPin": "MAOMING"
  }, {
    "CityID": 195,
    "CityName": "惠州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 19,
    "QuanPin": "HUIZHOU"
  }, {
    "CityID": 196,
    "CityName": "江门",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 19,
    "QuanPin": "JIANGMEN"
  }, {
    "CityID": 197,
    "CityName": "韶关",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 19,
    "QuanPin": "SHAOGUAN"
  }, {
    "CityID": 198,
    "CityName": "梅州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 19,
    "QuanPin": "MEIZHOU"
  }, {
    "CityID": 199,
    "CityName": "汕头",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 19,
    "QuanPin": "SHANTOU"
  }, {
    "CityID": 200,
    "CityName": "深圳",
    "HasCompany": true,
    "IsHot": 1,
    "ProID": 19,
    "QuanPin": "SHENZHEN",
    "SortID": 10
  }, {
    "CityID": 201,
    "CityName": "珠海",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 19,
    "QuanPin": "ZHUHAI"
  }, {
    "CityID": 202,
    "CityName": "佛山",
    "HasCompany": false,
    "IsHot": 1,
    "ProID": 19,
    "QuanPin": "FOSHAN"
  }, {
    "CityID": 203,
    "CityName": "肇庆",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 19,
    "QuanPin": "ZHAOQING"
  }, {
    "CityID": 204,
    "CityName": "湛江",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 19,
    "QuanPin": "ZHANJIANG"
  }, {
    "CityID": 205,
    "CityName": "中山",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 19,
    "QuanPin": "ZHONGSHAN"
  }, {
    "CityID": 206,
    "CityName": "河源",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 19,
    "QuanPin": "HEYUAN"
  }, {
    "CityID": 207,
    "CityName": "清远",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 19,
    "QuanPin": "QINGYUAN"
  }, {
    "CityID": 208,
    "CityName": "云浮",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 19,
    "QuanPin": "YUNFU"
  }, {
    "CityID": 209,
    "CityName": "潮州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 19,
    "QuanPin": "CHAOZHOU"
  }, {
    "CityID": 210,
    "CityName": "东莞",
    "HasCompany": true,
    "IsHot": 1,
    "ProID": 19,
    "QuanPin": "DONGGUAN",
    "SortID": 17
  }, {
    "CityID": 211,
    "CityName": "兰州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 22,
    "QuanPin": "LANZHOU"
  }, {
    "CityID": 212,
    "CityName": "金昌",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 22,
    "QuanPin": "JINCHANG"
  }, {
    "CityID": 213,
    "CityName": "白银",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 22,
    "QuanPin": "BAIYIN"
  }, {
    "CityID": 214,
    "CityName": "天水",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 22,
    "QuanPin": "TIANSHUI"
  }, {
    "CityID": 215,
    "CityName": "嘉峪关",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 22,
    "QuanPin": "JIAYUGUAN"
  }, {
    "CityID": 216,
    "CityName": "武威",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 22,
    "QuanPin": "WUWEI"
  }, {
    "CityID": 217,
    "CityName": "张掖",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 22,
    "QuanPin": "ZHANGYE"
  }, {
    "CityID": 218,
    "CityName": "平凉",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 22,
    "QuanPin": "PINGLIANG"
  }, {
    "CityID": 219,
    "CityName": "酒泉",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 22,
    "QuanPin": "JIUQUAN"
  }, {
    "CityID": 220,
    "CityName": "庆阳",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 22,
    "QuanPin": "QINGYANG"
  }, {
    "CityID": 221,
    "CityName": "定西",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 22,
    "QuanPin": "DINGXI"
  }, {
    "CityID": 222,
    "CityName": "陇南",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 22,
    "QuanPin": "LONGNAN"
  }, {
    "CityID": 223,
    "CityName": "临夏",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 22,
    "QuanPin": "LINXIA"
  }, {
    "CityID": 224,
    "CityName": "甘南",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 22,
    "QuanPin": "GANNAN"
  }, {
    "CityID": 225,
    "CityName": "成都",
    "HasCompany": true,
    "IsHot": 1,
    "ProID": 28,
    "QuanPin": "CHENGDU",
    "SortID": 9
  }, {
    "CityID": 226,
    "CityName": "攀枝花",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 28,
    "QuanPin": "PANZHIHUA"
  }, {
    "CityID": 227,
    "CityName": "自贡",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 28,
    "QuanPin": "ZIGONG"
  }, {
    "CityID": 228,
    "CityName": "绵阳",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 28,
    "QuanPin": "MIANYANG"
  }, {
    "CityID": 229,
    "CityName": "南充",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 28,
    "QuanPin": "NANCHONG"
  }, {
    "CityID": 230,
    "CityName": "达州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 28,
    "QuanPin": "DAZHOU"
  }, {
    "CityID": 231,
    "CityName": "遂宁",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 28,
    "QuanPin": "SUINING"
  }, {
    "CityID": 232,
    "CityName": "广安",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 28,
    "QuanPin": "GUANGAN"
  }, {
    "CityID": 233,
    "CityName": "巴中",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 28,
    "QuanPin": "BAZHONG"
  }, {
    "CityID": 234,
    "CityName": "泸州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 28,
    "QuanPin": "LUZHOU"
  }, {
    "CityID": 235,
    "CityName": "宜宾",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 28,
    "QuanPin": "YIBIN"
  }, {
    "CityID": 236,
    "CityName": "资阳",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 28,
    "QuanPin": "ZIYANG"
  }, {
    "CityID": 237,
    "CityName": "内江",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 28,
    "QuanPin": "NEIJIANG"
  }, {
    "CityID": 238,
    "CityName": "乐山",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 28,
    "QuanPin": "LESHAN"
  }, {
    "CityID": 239,
    "CityName": "眉山",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 28,
    "QuanPin": "MEISHAN"
  }, {
    "CityID": 240,
    "CityName": "凉山",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 28,
    "QuanPin": "LIANGSHAN"
  }, {
    "CityID": 241,
    "CityName": "雅安",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 28,
    "QuanPin": "YAAN"
  }, {
    "CityID": 242,
    "CityName": "甘孜",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 28,
    "QuanPin": "GANZI"
  }, {
    "CityID": 243,
    "CityName": "阿坝",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 28,
    "QuanPin": "ABA"
  }, {
    "CityID": 244,
    "CityName": "德阳",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 28,
    "QuanPin": "DEYANG"
  }, {
    "CityID": 245,
    "CityName": "广元",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 28,
    "QuanPin": "GUANGYUAN"
  }, {
    "CityID": 246,
    "CityName": "贵阳",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 29,
    "QuanPin": "GUIYANG"
  }, {
    "CityID": 247,
    "CityName": "遵义",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 29,
    "QuanPin": "ZUNYI"
  }, {
    "CityID": 248,
    "CityName": "安顺",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 29,
    "QuanPin": "ANSHUN"
  }, {
    "CityID": 249,
    "CityName": "黔南",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 29,
    "QuanPin": "QIANNAN"
  }, {
    "CityID": 250,
    "CityName": "黔东南",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 29,
    "QuanPin": "QIANDONGNAN"
  }, {
    "CityID": 251,
    "CityName": "铜仁",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 29,
    "QuanPin": "TONGREN"
  }, {
    "CityID": 252,
    "CityName": "毕节",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 29,
    "QuanPin": "BIJIEDIQU"
  }, {
    "CityID": 253,
    "CityName": "六盘水",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 29,
    "QuanPin": "LIUPANSHUI"
  }, {
    "CityID": 254,
    "CityName": "黔西南",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 29,
    "QuanPin": "QIANXINAN"
  }, {
    "CityID": 255,
    "CityName": "海口",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 20,
    "QuanPin": "HAIKOU"
  }, {
    "CityID": 256,
    "CityName": "三亚",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 20,
    "QuanPin": "SANYA"
  }, {
    "CityID": 257,
    "CityName": "五指山",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 20,
    "QuanPin": "WUZHISHAN"
  }, {
    "CityID": 258,
    "CityName": "琼海",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 20,
    "QuanPin": "QIONGHAI"
  }, {
    "CityID": 259,
    "CityName": "儋州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 20,
    "QuanPin": "DANZHOU"
  }, {
    "CityID": 260,
    "CityName": "文昌",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 20,
    "QuanPin": "WENCHANG"
  }, {
    "CityID": 261,
    "CityName": "万宁",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 20,
    "QuanPin": "WANNING"
  }, {
    "CityID": 262,
    "CityName": "东方",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 20,
    "QuanPin": "DONGFANG"
  }, {
    "CityID": 263,
    "CityName": "澄迈",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 20,
    "QuanPin": "CHENGMAIXIAN"
  }, {
    "CityID": 264,
    "CityName": "定安",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 20,
    "QuanPin": "DINGANXIAN"
  }, {
    "CityID": 265,
    "CityName": "屯昌",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 20,
    "QuanPin": "TUNCHANGXIAN"
  }, {
    "CityID": 266,
    "CityName": "临高",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 20,
    "QuanPin": "LINGAOXIAN"
  }, {
    "CityID": 267,
    "CityName": "白沙",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 20,
    "QuanPin": "BAISHA"
  }, {
    "CityID": 268,
    "CityName": "昌江",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 20,
    "QuanPin": "CHANGJIANG"
  }, {
    "CityID": 269,
    "CityName": "乐东",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 20,
    "QuanPin": "LEDONG"
  }, {
    "CityID": 270,
    "CityName": "陵水",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 20,
    "QuanPin": "LINGSHUI"
  }, {
    "CityID": 271,
    "CityName": "保亭",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 20,
    "QuanPin": "BAOTING"
  }, {
    "CityID": 272,
    "CityName": "琼中",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 20,
    "QuanPin": "QIONGZHONG"
  }, {
    "CityID": 273,
    "CityName": "西双版纳",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 30,
    "QuanPin": "XISHUANGBANNA"
  }, {
    "CityID": 274,
    "CityName": "德宏",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 30,
    "QuanPin": "DEHONG"
  }, {
    "CityID": 275,
    "CityName": "昭通",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 30,
    "QuanPin": "ZHAOTONG"
  }, {
    "CityID": 276,
    "CityName": "昆明",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 30,
    "QuanPin": "KUNMING"
  }, {
    "CityID": 277,
    "CityName": "大理",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 30,
    "QuanPin": "DALI"
  }, {
    "CityID": 278,
    "CityName": "红河",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 30,
    "QuanPin": "HONGHE"
  }, {
    "CityID": 279,
    "CityName": "曲靖",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 30,
    "QuanPin": "QUJING"
  }, {
    "CityID": 280,
    "CityName": "保山",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 30,
    "QuanPin": "BAOSHAN"
  }, {
    "CityID": 281,
    "CityName": "文山",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 30,
    "QuanPin": "WENSHAN"
  }, {
    "CityID": 282,
    "CityName": "玉溪",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 30,
    "QuanPin": "YUXI"
  }, {
    "CityID": 283,
    "CityName": "楚雄",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 30,
    "QuanPin": "CHUXIONG"
  }, {
    "CityID": 284,
    "CityName": "普洱",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 30,
    "QuanPin": "PUER"
  }, {
    "CityID": 285,
    "CityName": "临沧",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 30,
    "QuanPin": "LINCANG"
  }, {
    "CityID": 286,
    "CityName": "怒江",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 30,
    "QuanPin": "NUJIANG"
  }, {
    "CityID": 287,
    "CityName": "迪庆",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 30,
    "QuanPin": "DIQING"
  }, {
    "CityID": 288,
    "CityName": "丽江",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 30,
    "QuanPin": "LIJIANG"
  }, {
    "CityID": 289,
    "CityName": "海北",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 25,
    "QuanPin": "HAIBEI"
  }, {
    "CityID": 290,
    "CityName": "西宁",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 25,
    "QuanPin": "XINING"
  }, {
    "CityID": 291,
    "CityName": "海东",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 25,
    "QuanPin": "HAIDONG"
  }, {
    "CityID": 292,
    "CityName": "黄南",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 25,
    "QuanPin": "HUANGNAN"
  }, {
    "CityID": 293,
    "CityName": "海南",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 25,
    "QuanPin": "HAINAN"
  }, {
    "CityID": 294,
    "CityName": "果洛",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 25,
    "QuanPin": "GUOLUO"
  }, {
    "CityID": 295,
    "CityName": "玉树",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 25,
    "QuanPin": "YUSHU"
  }, {
    "CityID": 296,
    "CityName": "海西",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 25,
    "QuanPin": "HAIXI"
  }, {
    "CityID": 297,
    "CityName": "西安",
    "HasCompany": false,
    "IsHot": 1,
    "ProID": 23,
    "QuanPin": "XIAN"
  }, {
    "CityID": 298,
    "CityName": "咸阳",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 23,
    "QuanPin": "XIANYANG"
  }, {
    "CityID": 299,
    "CityName": "延安",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 23,
    "QuanPin": "YANAN"
  }, {
    "CityID": 300,
    "CityName": "榆林",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 23,
    "QuanPin": "YULIN1"
  }, {
    "CityID": 301,
    "CityName": "渭南",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 23,
    "QuanPin": "WEINAN"
  }, {
    "CityID": 302,
    "CityName": "商洛",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 23,
    "QuanPin": "SHANGLUO"
  }, {
    "CityID": 303,
    "CityName": "安康",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 23,
    "QuanPin": "ANKANG"
  }, {
    "CityID": 304,
    "CityName": "汉中",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 23,
    "QuanPin": "HANZHONG"
  }, {
    "CityID": 305,
    "CityName": "宝鸡",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 23,
    "QuanPin": "BAOJI"
  }, {
    "CityID": 306,
    "CityName": "铜川",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 23,
    "QuanPin": "TONGCHUAN"
  }, {
    "CityID": 307,
    "CityName": "防城港",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 21,
    "QuanPin": "FANGCHENGGANG"
  }, {
    "CityID": 308,
    "CityName": "南宁",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 21,
    "QuanPin": "NANNING"
  }, {
    "CityID": 309,
    "CityName": "崇左",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 21,
    "QuanPin": "CHONGZUO"
  }, {
    "CityID": 310,
    "CityName": "来宾",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 21,
    "QuanPin": "LAIBIN"
  }, {
    "CityID": 311,
    "CityName": "柳州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 21,
    "QuanPin": "LIUZHOU"
  }, {
    "CityID": 312,
    "CityName": "桂林",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 21,
    "QuanPin": "GUILIN"
  }, {
    "CityID": 313,
    "CityName": "梧州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 21,
    "QuanPin": "WUZHOU"
  }, {
    "CityID": 314,
    "CityName": "贺州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 21,
    "QuanPin": "HEZHOU"
  }, {
    "CityID": 315,
    "CityName": "贵港",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 21,
    "QuanPin": "GUIGANG"
  }, {
    "CityID": 316,
    "CityName": "玉林",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 21,
    "QuanPin": "YULIN"
  }, {
    "CityID": 317,
    "CityName": "百色",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 21,
    "QuanPin": "BAISE"
  }, {
    "CityID": 318,
    "CityName": "钦州",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 21,
    "QuanPin": "QINZHOU"
  }, {
    "CityID": 319,
    "CityName": "河池",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 21,
    "QuanPin": "HECHI"
  }, {
    "CityID": 320,
    "CityName": "北海",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 21,
    "QuanPin": "BEIHAI"
  }, {
    "CityID": 321,
    "CityName": "拉萨",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 31,
    "QuanPin": "LASA"
  }, {
    "CityID": 322,
    "CityName": "日喀则",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 31,
    "QuanPin": "RIKAZE"
  }, {
    "CityID": 323,
    "CityName": "山南",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 31,
    "QuanPin": "SHANNAN"
  }, {
    "CityID": 324,
    "CityName": "林芝",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 31,
    "QuanPin": "LINZHI"
  }, {
    "CityID": 325,
    "CityName": "昌都",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 31,
    "QuanPin": "CHANGDU"
  }, {
    "CityID": 326,
    "CityName": "那曲",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 31,
    "QuanPin": "NAQU"
  }, {
    "CityID": 327,
    "CityName": "阿里",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 31,
    "QuanPin": "ALI"
  }, {
    "CityID": 328,
    "CityName": "银川",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 26,
    "QuanPin": "YINCHUAN"
  }, {
    "CityID": 329,
    "CityName": "石嘴山",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 26,
    "QuanPin": "SHIZUISHAN"
  }, {
    "CityID": 330,
    "CityName": "吴忠",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 26,
    "QuanPin": "WUZHONG"
  }, {
    "CityID": 331,
    "CityName": "固原",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 26,
    "QuanPin": "GUYUAN"
  }, {
    "CityID": 332,
    "CityName": "中卫",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 26,
    "QuanPin": "ZHONGWEI"
  }, {
    "CityID": 333,
    "CityName": "塔城",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 24,
    "QuanPin": "TACHENG"
  }, {
    "CityID": 334,
    "CityName": "哈密",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 24,
    "QuanPin": "HAMI"
  }, {
    "CityID": 335,
    "CityName": "和田",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 24,
    "QuanPin": "HETIAN"
  }, {
    "CityID": 336,
    "CityName": "阿勒泰",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 24,
    "QuanPin": "ALETAI"
  }, {
    "CityID": 337,
    "CityName": "克孜勒苏",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 24,
    "QuanPin": "KEZILESU"
  }, {
    "CityID": 338,
    "CityName": "博尔塔拉",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 24,
    "QuanPin": "BOERTALA"
  }, {
    "CityID": 339,
    "CityName": "克拉玛依",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 24,
    "QuanPin": "KELAMAYI"
  }, {
    "CityID": 340,
    "CityName": "乌鲁木齐",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 24,
    "QuanPin": "WULUMUQI"
  }, {
    "CityID": 341,
    "CityName": "石河子",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 24,
    "QuanPin": "SHIHEZI"
  }, {
    "CityID": 342,
    "CityName": "昌吉",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 24,
    "QuanPin": "CHANGJI"
  }, {
    "CityID": 343,
    "CityName": "五家渠",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 24,
    "QuanPin": "WUJIAQU"
  }, {
    "CityID": 344,
    "CityName": "吐鲁番",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 24,
    "QuanPin": "TULUFAN"
  }, {
    "CityID": 345,
    "CityName": "巴音郭楞",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 24,
    "QuanPin": "BAYINGUOLENG"
  }, {
    "CityID": 346,
    "CityName": "阿克苏",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 24,
    "QuanPin": "AKESU"
  }, {
    "CityID": 347,
    "CityName": "阿拉尔",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 24,
    "QuanPin": "ALAER"
  }, {
    "CityID": 348,
    "CityName": "喀什",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 24,
    "QuanPin": "KASHI"
  }, {
    "CityID": 349,
    "CityName": "图木舒克",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 24,
    "QuanPin": "TUMUSHUKE"
  }, {
    "CityID": 350,
    "CityName": "伊犁",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 24,
    "QuanPin": "YILI"
  }, {
    "CityID": 351,
    "CityName": "呼伦贝尔",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 5,
    "QuanPin": "HULUNBEIER"
  }, {
    "CityID": 352,
    "CityName": "呼和浩特",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 5,
    "QuanPin": "HUHEHAOTE"
  }, {
    "CityID": 353,
    "CityName": "包头",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 5,
    "QuanPin": "BAOTOU"
  }, {
    "CityID": 354,
    "CityName": "乌海",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 5,
    "QuanPin": "WUHAI"
  }, {
    "CityID": 355,
    "CityName": "乌兰察布",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 5,
    "QuanPin": "WULANCHABU"
  }, {
    "CityID": 356,
    "CityName": "通辽",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 5,
    "QuanPin": "TONGLIAO"
  }, {
    "CityID": 357,
    "CityName": "赤峰",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 5,
    "QuanPin": "CHIFENG"
  }, {
    "CityID": 358,
    "CityName": "鄂尔多斯",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 5,
    "QuanPin": "EERDUOSI"
  }, {
    "CityID": 359,
    "CityName": "巴彦淖尔",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 5,
    "QuanPin": "BAYANNAOER"
  }, {
    "CityID": 360,
    "CityName": "锡林郭勒",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 5,
    "QuanPin": "XILINGUOLE"
  }, {
    "CityID": 361,
    "CityName": "兴安盟",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 5,
    "QuanPin": "XINGANMENG"
  }, {
    "CityID": 362,
    "CityName": "阿拉善",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 5,
    "QuanPin": "ALASHAN"
  }, {
    "CityID": 363,
    "CityName": "台北",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 32,
    "QuanPin": "TAIBEI"
  }, {
    "CityID": 364,
    "CityName": "高雄",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 32,
    "QuanPin": "GAOXIONG"
  }, {
    "CityID": 365,
    "CityName": "基隆",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 32,
    "QuanPin": "JILONG"
  }, {
    "CityID": 366,
    "CityName": "台中",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 32,
    "QuanPin": "TAIZHONG"
  }, {
    "CityID": 367,
    "CityName": "台南",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 32,
    "QuanPin": "TAINAN"
  }, {
    "CityID": 368,
    "CityName": "新竹",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 32,
    "QuanPin": "XINZHU"
  }, {
    "CityID": 369,
    "CityName": "嘉义",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 32,
    "QuanPin": "JIAYI"
  }, {
    "CityID": 370,
    "CityName": "澳门",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 33,
    "QuanPin": "AOMEN"
  }, {
    "CityID": 371,
    "CityName": "香港",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 34,
    "QuanPin": "XIANGGANG"
  }, {
    "CityID": 372,
    "CityName": "三沙",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 20,
    "QuanPin": "SANSHA"
  }, {
    "CityID": 373,
    "CityName": "铁门关",
    "HasCompany": false,
    "IsHot": 0,
    "ProID": 24,
    "QuanPin": "TIEMENGUAN"
  }]
  
  module.exports = CITY_LIST